FizzBuzz/FizzBuzz.Web/Models/FizzBuzzViewModel.cs
//-----------------------------------------------------------------------
// <copyright file="FizzBuzzViewModel.cs" company="Tata Consultancy Services">
//     Copyright (c) TCS. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
namespace FizzBuzz.Web.Models
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using PagedList;
   
    /// <summary>
    /// Model to view the output
    /// </summary>
    public class FizzBuzzViewModel
    {
        /// <summary>
        /// Gets or sets parameter number.
        /// </summary>
        [Required(ErrorMessage = "Please enter a number")]
        [Display(Name = "Enter Number")]
        [Range(1, 1000, ErrorMessage = "Enter a vaild number. Number should be in the range of 1 to 1000")]

        public int Number { get; set; }

        /// <summary>
        /// Gets or sets list FizzBuzzOutputList
        /// </summary>
        public IPagedList<string> FizzBuzzOutput { get; set; }
    }
}

FizzBuzz/FizzBuzz.Web/Controllers/FizzBuzzController.cs
//-----------------------------------------------------------------------
// <copyright file="FizzBuzzController.cs" company="Tata Consultancy Services">
//     Copyright (c) TCS. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
namespace FizzBuzz.Web.Controllers
{
    using System.Web.Mvc;
    using BusinessLogic;
    using Models;
    using PagedList;
    
    /// <summary>
    /// Fizz buzz controller.
    /// </summary>
    public class FizzBuzzController : Controller
    {
        /// <summary>
        /// Object creation
        /// </summary>
        private readonly IFizzBuzzExecutor fizzBuzz;

        /// <summary>
        /// Initializes a new instance of the <see cref="FizzBuzzController"/> class.
        /// </summary>
        /// <param name="fizzBuzz">Instance created to invoke the method</param>
        public FizzBuzzController(IFizzBuzzExecutor fizzBuzz)
        {
            this.fizzBuzz = fizzBuzz;
        }

        /// <summary>
        /// Action result Index
        /// </summary>
        /// <returns>Return FizzBuzzViewModel</returns>
        [HttpGet]
        public ActionResult Index()
        {
            var model = new FizzBuzzViewModel();
            return this.View(model);
        }

        /// <summary>
        /// Action result FizzBuzzOutput.
        /// </summary>
        /// <param name="model"> Instance to get the properties</param>
        /// <param name="page"> variable to get the pages</param>
        /// <returns>Returns output of fizz buzz list</returns>
        public ActionResult FizzBuzzOutput(FizzBuzzViewModel model, int page = 1)
        {
            if (this.ModelState.IsValid)
            {
                int pageSize = 20;
                var fizzBuzzOutput = this.fizzBuzz.GetFizzBuzzOutput(model.Number);
                model.FizzBuzzOutput = fizzBuzzOutput.ToPagedList(page, pageSize);
                return this.View("Index", model);
            }

            return this.View("Index", model);
        }
    }
}

FizzBuzz/FizzBuzz.Web/Views/FizzBuzz/Index.cshtml
@model FizzBuzz.Web.Models.FizzBuzzViewModel
@using PagedList.Mvc

@{
    ViewBag.Title = "Index";   
}



@using (Html.BeginForm("FizzBuzzOutput", "FizzBuzz"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">             
               @Html.TextBoxFor(model => model.Number, new { @Value = (@Model.Number == 0) ? "" : @Model.Number.ToString() })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
        </div>
    </div>
    <div class="form-group">

        @if (Model.FizzBuzzOutput != null)
        {
            <table>

                @for (var i = 0; i < Model.FizzBuzzOutput.Count; i++)
                {
                    
                    <tr>
                        <td>
                        @foreach(var item in Model.FizzBuzzOutput[i].Split(' '))
                            {
                                <span class="@item"> @item </span>
                            }
                         </td>
                    </tr>
                   
                }

                </table>
            
                <div class="pagination">
                    Page @(Model.FizzBuzzOutput.PageCount < Model.FizzBuzzOutput.PageNumber ? 0 : Model.FizzBuzzOutput.PageNumber)
                    of @Model.FizzBuzzOutput.PageCount
                    @Html.PagedListPager(Model.FizzBuzzOutput,
                page => Url.Action("FizzBuzzOutput", "FizzBuzz", new { Model.Number, page }))
                </div>
            
        }
        </div>

}

FizzBuzz/FizzBuzz.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>Fizz  <span class="span"> Buzz</span><span class="app"> Application</span></header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My Fizz Buzz Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryval")
      
        @RenderSection("scripts", required: false)
    </body>
</html>